<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>sia</groupId>
  	<artifactId>taco-cloud-parent</artifactId>
    <version>0.0.17-SNAPSHOT</version>
    <packaging>pom</packaging>

    <parent>
  		<groupId>org.springframework.boot</groupId>
  		<artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.18</version>
  		<relativePath/>
  	</parent>

    <properties>
      <maven.compiler.source>21</maven.compiler.source>
      <maven.compiler.target>21</maven.compiler.target>
      <tacocloud.version>${project.version}</tacocloud.version>
      <selenium.version>4.8.3</selenium.version>
      <selenium-htmlunit.version>4.8.3</selenium-htmlunit.version>
      <htmlunit.version>2.70.0</htmlunit.version>
    </properties>

    <dependencyManagement>
      <dependencies>
        <dependency>
          <groupId>commons-io</groupId>
          <artifactId>commons-io</artifactId>
          <version>2.16.1</version>
        </dependency>

        <dependency>
          <groupId>io.projectreactor</groupId>
          <artifactId>reactor-core</artifactId>
        </dependency>

      </dependencies>
    </dependencyManagement>

    <modules>
      <module>tacocloud</module>
      <module>tacocloud-api</module>
      <module>tacocloud-data-mongodb</module>
      <module>tacocloud-domain-mongodb</module>
      <module>tacocloud-email</module>
      <module>tacocloud-jmx</module>
      <module>tacocloud-kitchen</module>
      <module>tacocloud-messaging-jms</module>
      <module>tacocloud-messaging-kafka</module>
      <module>tacocloud-messaging-rabbitmq</module>
      <module>tacocloud-messaging-noop</module>
      <module>tacocloud-restclient</module>
      <module>tacocloud-security</module>
      <module>tacocloud-web</module>
      <module>tacocloud-ui</module>
    </modules>

</project>
