spring:
  artemis:
    host: ${ARTEMIS_HOST:localhost}
    port: ${ARTEMIS_PORT:61616}
    user: ${ARTEMIS_USER:}
    password: ${ARTEMIS_PASSWORD:}
    embedded:
      enabled: false
tacocloud:
  messaging:
    jms:
      destination: ${JMS_ORDER_DESTINATION:tacocloud.order.queue}
